Repository ZB-Keyword/Keyword-BackEnd, pull requests merged in 2024-01, with the labels that each got.

#21 [Feat #8] 시큐리티 관련 설정
  build.gradle
  src/main/java/DevHeaven/keyword/common/exception/GlobalExceptionHandler.java
  src/main/java/DevHeaven/keyword/common/exception/JwtException.java
  src/main/java/DevHeaven/keyword/common/exception/dto/ErrorResponse.java
  src/main/java/DevHeaven/keyword/common/exception/type/ErrorCode.java
  src/main/java/DevHeaven/keyword/common/exception/util/ErrorResponseUtils.java
  src/main/java/DevHeaven/keyword/common/security/JwtAccessDeniedHandler.java
  src/main/java/DevHeaven/keyword/common/security/JwtAuthenticationEntryPoint.java
  src/main/java/DevHeaven/keyword/common/security/JwtAuthenticationFilter.java
  src/main/java/DevHeaven/keyword/common/security/JwtExceptionFilter.java
  src/main/java/DevHeaven/keyword/common/security/JwtUtils.java
  src/main/java/DevHeaven/keyword/common/security/dto/TokenResponse.java
  src/main/java/DevHeaven/keyword/config/SecurityConfig.java
  src/main/java/DevHeaven/keyword/domain/member/controller/MemberController.java
  src/main/java/DevHeaven/keyword/domain/member/dto/MemberAdapter.java
  src/main/java/DevHeaven/keyword/domain/member/dto/request/SigninRequest.java
  src/main/java/DevHeaven/keyword/domain/member/dto/request/SignupRequest.java
  src/main/java/DevHeaven/keyword/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/DevHeaven/keyword/domain/member/dto/response/MyInfoResponse.java
  src/main/java/DevHeaven/keyword/domain/member/dto/response/SignupResponse.java
  src/main/java/DevHeaven/keyword/domain/member/entity/Member.java
  src/main/java/DevHeaven/keyword/domain/member/repository/MemberRepository.java
  src/main/java/DevHeaven/keyword/domain/member/service/MemberDetailsService.java
  src/main/java/DevHeaven/keyword/domain/member/service/MemberService.java
  src/main/java/DevHeaven/keyword/domain/member/type/MemberRole.java
  src/main/java/DevHeaven/keyword/domain/member/type/MemberStatus.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V2__member_add_role.sql
Labels: feature

#42 [Feat #41] 스케줄 생성 기능 구현
  src/main/java/DevHeaven/keyword/domain/member/service/MemberService.java
  src/main/java/DevHeaven/keyword/domain/schedule/controller/ScheduleController.java
  src/main/java/DevHeaven/keyword/domain/schedule/dto/request/ScheduleCreateRequest.java
  src/main/java/DevHeaven/keyword/domain/schedule/dto/response/ScheduleCreateResponse.java
  src/main/java/DevHeaven/keyword/domain/schedule/service/ScheduleService.java
Labels: feature

#46 [Feature #37] member 프로필 이미지 수정 기능
  src/main/java/DevHeaven/keyword/domain/chat/entity/Chat.java
  src/main/java/DevHeaven/keyword/domain/member/controller/MemberController.java
  src/main/java/DevHeaven/keyword/domain/member/dto/request/ModifyPasswordRequest.java
  src/main/java/DevHeaven/keyword/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/DevHeaven/keyword/domain/member/dto/response/MyInfoResponse.java
  src/main/java/DevHeaven/keyword/domain/member/entity/Member.java
  src/main/java/DevHeaven/keyword/domain/member/service/MemberService.java
  src/main/java/DevHeaven/keyword/domain/schedule/service/ScheduleService.java
  src/main/resources/db/migration/V4__member_modify_imageUrl.sql
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/DevHeaven/keyword/support/fixture/MemberFixture.java
Labels: feature

#56 [Feat #55] 친구 검색 기능 임시 구현
  src/main/java/DevHeaven/keyword/domain/friend/controller/FriendController.java
  src/main/java/DevHeaven/keyword/domain/friend/service/FriendService.java
  src/main/java/DevHeaven/keyword/domain/friend/type/FriendState.java
  src/main/java/DevHeaven/keyword/domain/member/repository/MemberRepository.java
Labels: feature

#79 [Feat #49] 소셜 로그인
  src/main/java/DevHeaven/keyword/common/exception/type/ErrorCode.java
  src/main/java/DevHeaven/keyword/common/exception/util/ResponseUtils.java
  src/main/java/DevHeaven/keyword/common/security/JwtAccessDeniedHandler.java
  src/main/java/DevHeaven/keyword/common/security/JwtAuthenticationEntryPoint.java
  src/main/java/DevHeaven/keyword/common/security/JwtExceptionFilter.java
  src/main/java/DevHeaven/keyword/common/security/OAuth2SuccessHandler.java
  src/main/java/DevHeaven/keyword/config/SecurityConfig.java
  src/main/java/DevHeaven/keyword/domain/member/controller/MemberController.java
  src/main/java/DevHeaven/keyword/domain/member/controller/OAuthController.java
  src/main/java/DevHeaven/keyword/domain/member/controller/SocialLoginController.java
  src/main/java/DevHeaven/keyword/domain/member/dto/OAuthMemberAdapter.java
  src/main/java/DevHeaven/keyword/domain/member/dto/PrincipalDetails.java
  src/main/java/DevHeaven/keyword/domain/member/dto/provider/NaverUserInfo.java
  src/main/java/DevHeaven/keyword/domain/member/dto/provider/OAuth2UserInfo.java
  src/main/java/DevHeaven/keyword/domain/member/dto/response/MyInfoResponse.java
  src/main/java/DevHeaven/keyword/domain/member/entity/Member.java
  src/main/java/DevHeaven/keyword/domain/member/service/MemberService.java
  src/main/java/DevHeaven/keyword/domain/member/service/OAuth2UserService.java
  src/main/java/DevHeaven/keyword/domain/member/service/oauth/provider/NaverUserInfo.java
  src/main/java/DevHeaven/keyword/domain/member/service/oauth/provider/OAuth2UserInfo.java
  src/main/java/DevHeaven/keyword/domain/member/type/MemberProvider.java
Labels: feature

#91 [Fix] OAuth redirect url 을 배포 환경으로 수정
  src/main/java/DevHeaven/keyword/common/security/OAuth2SuccessHandler.java
Labels: fix

#96 [Fix] OAuth permit url 추가
  src/main/java/DevHeaven/keyword/config/SecurityConfig.java
Labels: fix, refactoring
